server:
  port: 9001
spring:
  application:
    name: user-skadihouse-service
  data:
      mongodb:
          uri: mongodb://localhost:27017
          database: user_subscription
  jackson:
    serialization:
      INDENT_OUTPUT: true