server:
  port: 9000
spring:
  application:
    name: house-info-service
  data:
      mongodb:
          uri: mongodb://localhost:27017
          database: zillow_house_info
  jackson:
    serialization:
      INDENT_OUTPUT: true