server:
  port: 9001
spring:
  application:
    name: user-skadihouse-service
  data:
      mongodb:
          uri: mongodb://houseuser:helloworld@localhost:27017/zillow_house_info
  jackson:
    serialization:
      INDENT_OUTPUT: true